[package]
name = "sharding-with-token-coordination"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.42", features = ["full"] }
